### PR TITLE
[Rapid7 InsightVM] Fix `token` Parameter BC Issue

### PR DESCRIPTION
**Pull request by MichaelYochpaz**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-24552)

## Description
Fix `token` parameter having unexpected values in some cases (string instead of dict, and empty string instead of None) after upgrading to 1.2.0+ and using a previous instance.

### CODE REVIEW

File: Packs/Rapid7_Nexpose/ReleaseNotes/1_2_9.md [hunk 1]
```diff
@@ -0,0 +1,7 @@
+
+#### Integrations
+
+##### Rapid7 InsightVM
+
+- Fixed an issue where usage of the **token** parameter may cause a Python error ("'str' object has no attribute 'get'"), or authentication issues, after upgrading the pack from versions that are < 1.2.0.
```
Comment (bziser) [inline Packs/Rapid7_Nexpose/ReleaseNotes/1_2_9.md:6]:
```suggestion
- Fixed an issue where usage of the **token** parameter may cause aמ error or authentication issues.
```

File: Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py [hunk 2]
```diff
@@ -5357,11 +5357,23 @@ def main():  # pragma: no cover
...
+        if params.get("token") and isinstance(params["token"], str):
+            token = params["token"]
+
+        else:
+            if identifier := params.get("token", {}).get("identifier"):
+                token = identifier
+
+            else:  # If token.identifier is an empty string, use None instead.
+                token = None
+
```
Comment (bziser) [inline Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py:5372]:
```suggestion
        token = None
        if params.get("token"):
               token = params["token"] if isinstance(params["token"], str) else params.get("token", {}).get("identifier")
```

**Review by bziser — COMMENTED** [review]
Great

File: Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py [hunk 3]
```diff
@@ -5357,11 +5358,22 @@ def main():  # pragma: no cover
...
+        # A workaround for fixing compatibility issues when upgrading existing instances that are < 1.2.0.
+        # ('token' field was converted from type 0 to type 9)
+        token = None
+
+        if params.get("token"):
+            if isinstance(params["token"], str):
+                token = params["token"]
+
+            elif params["token"].get("identifier"):
+                token = params["token"]["identifier"]
```
Comment (bziser) [inline Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py:5370]:
```suggestion
            else:
                token = params["token"]["identifier"]
```
why needed the elif?

Comment (MichaelYochpaz) [reply Packs/Rapid7_Nexpose/Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py:5370]:
```python
        token = None

        if params.get("token"):
            if isinstance(params["token"], str):
                token = params["token"]

            elif params["token"].get("identifier"):
                token = params["token"]["identifier"]
```

If there is no `token` (can happen in case it's of type `str`) or `token["identifier"]` does not exist, or is an empty string, `token` will remain as `None` (this is mainly to avoid a case where `identifier` will be able to have an empty string value, which can cause further bugs in the future)

**Review by bziser — APPROVED** [review]
